// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJcnRa9JW4ptUEe_y874vbjx7X99dIsyg',
    appId: '1:675483548792:web:b263008b9985c219cc418d',
    messagingSenderId: '675483548792',
    projectId: 'food-delivery-1c734',
    authDomain: 'food-delivery-1c734.firebaseapp.com',
    storageBucket: 'food-delivery-1c734.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUJXKJbpTiUPQ7ciOldVYsQjk54JwgaHA',
    appId: '1:675483548792:android:068e1b58ad8b918ecc418d',
    messagingSenderId: '675483548792',
    projectId: 'food-delivery-1c734',
    storageBucket: 'food-delivery-1c734.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYCgJg8QmKmXWHpDrS9L7ogNri8mHrQvg',
    appId: '1:675483548792:ios:deff321d299d6264cc418d',
    messagingSenderId: '675483548792',
    projectId: 'food-delivery-1c734',
    storageBucket: 'food-delivery-1c734.appspot.com',
    iosBundleId: 'com.codeforany.foodDelivery',
  );
}
